Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
  
    # Provider-specific configuration
    config.vm.provider :libvirt do |libvirt|
      libvirt.memory = 32768  # 32GB RAM
      libvirt.cpus = 10       # 10 CPUs
  
      # Set disk size to 100GB
      libvirt.machine_virtual_size = 100
  
      # Enable KVM nested virtualization
      libvirt.nested = true
  
      # Enable CPU host passthrough for better performance
      libvirt.cpu_mode = "host-passthrough"
    end
  
    # Network configuration
    config.vm.network "forwarded_port", guest: 2376, host: 2376, protocol: "tcp"
  
    # Sync folder configuration
    # The path './vagrant' in the host will be synced to '/home/vagrant' in the guest
    config.vm.synced_folder "./vagrant", "/home/vagrant"
  end