apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: block-flash-encrypted-post
spec:
  kprobes:
    - call: "__sys_connect"
      return: false
      syscall: true
      args:
        - index: 0
          type: "string"
        - index: 1
          type: "string"
      selectors:
        - matchArgs:
          - index: 0
            operator: "Equal"
            values:
              - "/flash/addencrypted2"
          - index: 1
            operator: "Equal"
            values:
              - "POST"
      message: "Detected potential RCE attempt via /flash/addencrypted2"