apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: memory-protection
spec:
  kprobes:
    - call: "security_mmap_addr"
      return: false
      syscall: false
      args:
        - index: 0
          type: "int"
      selectors:
        - matchArgs:
          - index: 0
            operator: "Equal"
            values:
              - "4"  # PROT_EXEC
      message: "Executable memory mapping attempted"