apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: monitor-process-creation
spec:
  kprobes:
    - call: "sys_execve"
      return: false
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
          - index: 0
            operator: "NotEqual"
            values:
              - "/usr/local/bin/flash"
      message: "Process creation detected outside of flash binary"