apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: network-anomaly-detection
spec:
  kprobes:
    - call: "security_socket_connect"
      return: false
      syscall: false
      args:
        - index: 0
          type: "sock"  # Changed from sockaddr to sock
      selectors:
        - matchArgs:
          - index: 0
            operator: "NotEqual"
            values:
              - "127.0.0.1"
      message: "Non-localhost connection detected"