apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: file-integrity-monitor
spec:
  kprobes:
    - call: "security_inode_create"
      return: false
      syscall: false
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
          - index: 0
            operator: "Prefix"  # Changed from Contains to Prefix
            values:
              - "/flash/"
      message: "File creation detected in /flash directory"