apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: network-segmentation
spec:
  kprobes:
    - call: "__sys_bind"
      return: false
      syscall: true
      args:
        - index: 0
          type: "fd"
        - index: 1
          type: "sock"
      selectors:
        - matchArgs:
          - index: 1
            operator: "SPortPriv"  # Changed from NotInRange to SPortPriv to catch privileged ports
            values:
              - "true"
      message: "Binding to restricted port detected"