apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: shell-execution-prevention
spec:
  kprobes:
    - call: "do_execve"
      return: false
      syscall: false
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
          - index: 0
            operator: "Equal"
            values:
              - "/bin/sh"
              - "/bin/bash"
      message: "Shell execution attempted"
