apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: network-connection-limit
spec:
  kprobes:
    - call: "__sys_connect"
      return: false
      syscall: true
      args:
        - index: 0
          type: "int"
      rateLimit:
        interval: "1s"
        maxRate: 10
      message: "Connection rate limit exceeded"