//
// @file : utils.c
// @author : Isu Kim @ dev.gooday2die@gmail.com | Github @ https://github.com/gooday2die
// @brief : A file that implements all functions defined by utils.c
//

#include "utils.h"


/**
 * A function that gets $PATH environment.
 * This function will parse $PATH environment that was retrieved by getenv function and delimit by strtok_r function.
 * Also, this will allocate a array of strings using malloc. Don't forget to free it!
 * @param len The address of integer to store length of total path strings. (Since this is C, term 'string' is 'c_str')
 * @return Returns array of strings. The array is NULL terminated.
 */
const char** getPaths(int* len) {
    char* env; // For storing result from getenv.
    char* tmpStr; // For storing current delimited string.
    char* remaining; // For storing remaining string.
    int count = 1; // For storing total count of PATHs. (I am pretty sure nobody has more PATHs than integer range)

    // Generate a buffer for temporary storing all delimited tokens.
    // Since we do not know how many paths are there, we are going to dump this tmpBuffer into malloced variable later.
    const char* tmpBuffer[BUFFER_SIZE];
    const char** paths = NULL;

    env = getenv("PATH"); // Get env
    tmpStr = strtok_r(env, ":", &remaining); // strtok_r with original string
    tmpBuffer[0] = tmpStr;

    while (tmpStr != NULL) { // Iterate till the end of delimited ones.
        tmpStr = strtok_r(NULL, ":", &remaining); // Set delimiter as :
        tmpBuffer[count] = tmpStr; // Store temporary.
        // printf("[+] Path %d : %s\n", count, tmpBuffer[count]); // For debug purpose.
        count++;
    }

    // Dump tmpBuffer into return paths using memcpy.
    paths = (const char**) malloc(sizeof(const char*) * count);
    memcpy(paths, tmpBuffer, (sizeof(const char*) * count));

    // Set return values and return.
    *len = count;
    return paths;
}

/**
 * A function that parses command.
 * This will parse command with delimiter of a whitespace.
 * For example, if command was "ls -a -l", this will return {"ls", "-a", "-l", NULL} as result.
 * @param len The address of integer to store length of total path strings. (Since this is C, term 'string' is 'c_str')
 * @param cmd The string that needs to be parsed
 * @return The array of strings of command. The array is NULL terminated.
 */
const char** parseCommand(int* len, const char* cmd) {
    char* tmpStr; // For storing current delimited string.
    char* remaining; // For storing remaining string.
    int count = 1; // For storing total count of PATHs. (I am pretty sure nobody has more PATHs than integer range)

    // Generate a buffer for temporary storing all delimited tokens.
    // Since we do not know how many paths are there, we are going to dump this tmpBuffer into malloced variable later.
    const char* tmpBuffer[BUFFER_SIZE];
    const char** paths = NULL;

    // Just casting const char* into char* is dangerous and causes segfault. Thus, will be using strdup.
    // Check https://stackoverflow.com/questions/25549562/how-to-convert-const-char-to-char-in-c for more information.
    tmpStr = strtok_r(strdup(cmd), " ", &remaining); // strtok_r with original string
    tmpBuffer[0] = tmpStr;

    while (tmpStr != NULL) { // Iterate till the end of delimited ones.
        tmpStr = strtok_r(NULL, " ", &remaining); // Set delimiter as whitespace
        tmpBuffer[count] = tmpStr; // Store temporary.
        count++;
    }

    // Dump tmpBuffer into return paths using memcpy.
    paths = (const char**) malloc(sizeof(const char*) * count);
    memcpy(paths, tmpBuffer, (sizeof(const char*) * count));

    // Set return values and return.
    *len = count;
    return paths;
}

/**
 * A fun function that prints out SiSh Banner!
 * Ascii Art was generated by https://patorjk.com/software/taag/ with font Colossal.
 *
 */
void printBanner() {
    printf("\n");
    printf(" .d8888b.  d8b  .d8888b.  888    888 \n");
    printf("d88P  Y88b Y8P d88P  Y88b 888    888 \n");
    printf("Y88b.          Y88b.      888    888 \n");
    printf(" \"Y888b.   888  \"Y888b.   8888888888 \n");
    printf("    \"Y88b. 888     \"Y88b. 888    888 \n");
    printf("      \"888 888       \"888 888    888 \n");
    printf("Y88b  d88P 888 Y88b  d88P 888    888 \n");
    printf(" \"Y8888P\"  888  \"Y8888P\"  888    888 \n");
    printf("\n                      My Simple Shell\n");
    printf("             For OS HW 1\n\n");
}


void printBye() {
    printf("\n .d8888b.                         888      888                        \n");
    printf("d88P  Y88b                        888      888                        \n");
    printf("888    888                        888      888                        \n");
    printf("888         .d88b.   .d88b.   .d88888      88888b.  888  888  .d88b.  \n");
    printf("888  88888 d88\"\"88b d88\"\"88b d88\" 888      888 \"88b 888  888 d8P  Y8b \n");
    printf("888    888 888  888 888  888 888  888      888  888 888  888 88888888 \n");
    printf("Y88b  d88P Y88..88P Y88..88P Y88b 888      888 d88P Y88b 888 Y8b.     \n");
    printf(" \"Y8888P88  \"Y88P\"   \"Y88P\"   \"Y88888      88888P\"   \"Y88888  \"Y8888  \n");
    printf("                                                         888          \n");
    printf("                                                    Y8b d88P          \n");
    printf("                                                     \"Y88P\"           \n\n");
}


/**
 * A function that prints out array of string until it hits NULL.
 * This function is for debug purpose.
 * This function is for const char**.
 * @param strings The array of strings to look for.
 */
void printStringArr_cc(const char** strings) {
    int count = 0;
    while(strings[count] != NULL) {
        printf("[+] Count %d : %s\n", count, strings[count]);
        count++;
    }
    printf("[+] Count %d : %s\n", count, strings[count]);

}

/**
 * A function that prints out array of string until it hits NULL.
 * This function is for debug purpose.
 * This function is for char**
 * @param strings The array of strings to look for.
 */
void printStringArr_c(char** strings) {
    int count = 0;
    while(strings[count] != NULL) {
        printf("[+] Count %d : %s\n", count, strings[count]);
        count++;
    }
    printf("[+] Count %d : %s\n", count, strings[count]);
}