apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "block-flash-addencrypted2"
spec:
  endpointSelector:
    matchLabels:
      app: pyload-non
  ingress:
  - fromEndpoints:
    - {}
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        http:
        - method: "POST"
          path: "^/flash/addencrypted2$"
          headers: ["Content-Type: application/json"]