apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "egress-restriction"
spec:
  endpointSelector:
    matchLabels:
      app: pyload-non
  egress:
  - toEndpoints:
    - matchLabels:
        k8s:app: allowed-service
  - toFQDNs:
    - matchNames:
      - "api.legitimate-service.com"