apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "restrict-http-methods"
spec:
  endpointSelector:
    matchLabels:
      app: pyload-non
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        l7proto: http
        l7:
        - method: "GET"
          path: "/api/.*"
        - method: "POST"
          path: "/api/auth/.*"
