#==== new file #====
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "payload-size-limit"
spec:
  endpointSelector:
    matchLabels:
      app: vulnerable-app
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        l7proto: http
        l7:
        - headers: "Content-Length: 1-1000"
