apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "require-content-type"
spec:
  endpointSelector:
    matchLabels:
      app: pyload-non
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        l7proto: http
        l7:
        - headers: "Content-Type: application/json"