apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "block-suspicious-headers"
spec:
  endpointSelector:
    matchLabels:
      app: vulnerable-app
  ingress:
  - toPorts:
    - ports:
      - port: "80"
        protocol: TCP
      rules:
        l7proto: http
        l7:
        - method: "!GET"
          headers: "!X-Forwarded-For,!X-Remote-Addr"