apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "enforce-tls"
spec:
  endpointSelector:
    matchLabels:
      app: pyload-non
  ingress:
  - toPorts:
    - ports:
      - port: "443"
        protocol: TCP